language: cpp
compiler:
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - g++-4.9
    - libstdc++-4.9-dev
    - autoconf
    - automake
    - autotools-dev
    - libtool
    - pkg-config
    - zlib1g-dev
    - libcunit1-dev
    - libssl-dev
    - libxml2-dev
    - libev-dev
    - libevent-dev
    - libjansson-dev
    - libjemalloc-dev
    - cmake
    - cmake-data
before_install:
  - $CC --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CC --version
  - go version
  - cmake --version
before_script:
  # First build spdylay, since integration tests require it.
  # spdylay is going to be built under third-party/spdylay
  - cd third-party
  - git clone https://github.com/tatsuhiro-t/spdylay.git
  - cd spdylay
  - autoreconf -i
  - ./configure --disable-src --disable-examples
  - make check
  - export SPDYLAY_HOME=$PWD
  - cd ../..
  # Now build nghttp2
  - autoreconf -i
script:
  - ./releasechk
  - rm -rf nghttp2-1.9.0-DEV
  - tar xf nghttp2-1.9.0-DEV.tar.gz
  - cd nghttp2-1.9.0-DEV
  - cmake -DENABLE_WERROR=1 -DWITH_MRUBY=1 -DWITH_NEVERBLEED=1 -DSPDYLAY_INCLUDE_DIR="$SPDYLAY_HOME/lib/includes" -DSPDYLAY_LIBRARY="$SPDYLAY_HOME/lib/.libs/libspdylay.so"
  - make
  - make check
  - cd integration-tests
  - export GOPATH="$PWD/integration-tests/golang"
  - make itprep
  - make it
